apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
  namespace: web-ns
spec:
  ports:
    - port: 80
  selector:
    app: admin
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
  namespace: web-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: admin
        tier: frontend
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: admin
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: abc@123
        - name: PMA_HOST
          value: database1
        ports:
        - containerPort: 80
          name: admin
