apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
  namespace: web-ns
spec:
  ports:
    - port: 80
  selector:
    app: webserver
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
  namespace: web-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
        tier: frontend
    spec:
      containers:
      - image: mohitaga98/webserver
        name: webserver
        ports:
        - containerPort: 80
          name: webserver
        volumeMounts:
        - name: webserver-persistent
          mountPath: /var/www/html
      volumes:
      - name: webserver-persistent
        persistentVolumeClaim:
          claimName: efs-web
