apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-ns

secretGenerator:
- name: mysql-pass
  literals:
  - password=abc@123

resources:
- namespace.yaml
- create-efs-provisioner.yaml
- create-rbac.yaml
- create-storage.yaml
- deploy-mysql.yaml
- admin.yaml
- deploy-webserver.yaml
